routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
header('Access-Control-Allow-Origin: *');

Route::get('/backend/login', 'LoginController@index')->name('login');
Route::post('/backend/login','Auth\LoginController@login');
Route::get('/backend/logout', 'LogoutController@index')->name('logout');
Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::any('users/data', 'UserController@getData')->name('users.getData');
	Route::resource('users', 'UserController');


	Route::any('userlist/data', 'UserListController@getData')->name('userlist.getData');
	Route::resource('userlist','UserListController');
	Route::any('luckyitems/data', 'LuckyItemController@getData')->name('luckyitems.getData');
	Route::resource('luckyitems', 'LuckyItemController');
	//Gallery route
	Route::any('galleries/data', 'GalleryController@getData')->name('galleries.getData');
	Route::resource('galleries', 'GalleryController');

	Route::any('footballTeamList/data', 'FootballTeamListController@getData')->name('footballTeamList.getData');
	Route::resource('footballTeamList','FootballTeamListController');

	Route::any('map/data', 'MapController@getData')->name('map.getData');
	Route::resource('map','MapController');

	Route::any('sliders/data', 'SliderController@getData')->name('sliders.getData');
	Route::resource('sliders','SliderController');

	Route::any('matches/data', 'MatchController@getData')->name('matches.getData');
	Route::resource('matches','MatchController');

	Route::any('videos/data', 'VideoController@getData')->name('videos.getData');
	Route::resource('videos','VideoController');
	
	Route::resource('settings','SettingController');
	
	Route::any('teamList/data', 'TeamListController@getData')->name('teamList.getData');
	Route::resource('teamList','TeamListController');

	Route::any('winning/data', 'WinningController@getData')->name('winning.getData');
	Route::resource('winning','WinningController');
});
Route::get('/','HomePageController@promo');
Route::post('/confirm_yes','HomePageController@confirm');
Route::get('/sess_destroy','HomePageController@destory_session');
Route::get('/home','HomePageController@index')->name('homepage');
Route::resource('userReg','UserReqRegController');
Route::get('/customerlogin','UserReqRegController@showLogin')->name('customer_login');
Route::post('/customerlogin','UserReqRegController@login')->name('customer_login');

Route::get('/customerlogout','UserReqRegController@logout')->name('customer_logout');
Route::group(['middleware' => 'forntendauth:customer'], function () {
	Route::get('/teamedit','HomePageController@teamEdit')->name('teamedit');
	Route::get('/playerlistedit/{id}','HomePageController@playerlistedit')->name('playeredit');
	Route::post('/teamupdate/{id}','HomePageController@teamupdate')->name('teamupdate');
Route::post('/playerlistupdate/{id}','HomePageController@playerlistupdate')->name('playerupdate');
Route::resource('/footballTeamReg','FootballTeamRegController');
Route::get('/teamplayerlist','HomePageController@playerlist')->name('playerlist');
});
Route::get('/luckydraw','HomePageController@luckydraw')->name('luckydraw');

Route::get('/gallery','HomePageController@gallery')->name('gallery');
Route::get('/gallery/{id}','HomePageController@gallery_detail')->name('gallery_detial');

//video gallery
Route::get('/videogallery','HomePageController@videoGallery')->name('videogallery');
Route::get('/videogallery/{id}','HomePageController@videoGallery_detail')->name('videoGallery_detail');
Route::get('/getLuckyItem','HomePageController@getLuckyItem')->name('getluckyitem');
Route::get('/checkLogin','PromotionController@checkLogin')->name('checkLogin');
Route::post('/winningStore','PromotionController@winningStore')->name('winningStore');


Route::resource('/map','MapController');

Route::get('/promotions','HomePageController@promotions')->name('promotions');
Route::get('/term_condition','HomePageController@term_condition')->name('term_condition');
Route::get('/eventlist','HomePageController@eventList')->name('eventlist');
Route::get('/eventdetail/{id}','HomePageController@eventDetail')->name('eventdetail');
Route::get('/matchlist/{id}','HomePageController@matchList')->name('matchList');
//facebook loing

Route::get('facebook_login', 'UserReqRegController@redirectToProvider')->name('fb_login');
Route::get('facebook_login/callback', 'UserReqRegController@handleProviderCallback');

app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
class Video extends Model implements HasMedia
{
    //
    use SoftDeletes,HasMediaTrait;

     protected $fillable = [
            'title','description'
    ];


    public function getMediaUrl()
    {
        if ($this->hasMedia('video')) {
            return $this->getFirstMediaUrl('video');
        }
        
    }
    public function getMediaImageUrl()
    {
        if ($this->hasMedia('videoimage')) {
            return $this->getFirstMediaUrl('videoimage');
        }
        
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\VideoRequest;
use App\Repositories\VideoRepo;
use Illuminate\Validation\Rule; 
use Session;

class VideoController extends Controller
{
    protected $videoRepo;

    public function __construct(VideoRepo $videoRepo) {
        $this->videoRepo = $videoRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        
            return view('video.index');     
       
    }

    public function getData(Request $request)
    {
        return $this->videoRepo->getVideos($request);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('video.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VideoRequest $request)
    {      
           
        $video = $this->videoRepo->save($request);

        Session::flash('message', 'You have successfully Insert Video.');
        return redirect()->route('videos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {   
        
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        
        $video = $this->videoRepo->getVideo($id);
        return view('video.edit', compact('video')); 
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        
        $video = $this->videoRepo->save($request,$id);
        
        Session::flash('message', 'You have successfully Update Video.');
        return redirect()->route('videos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $deleted = $this->videoRepo->deleteVideo($id);

            
        if($deleted){
            $data = [
            'status' => "success",
            'message' => "Delete Success"
            ];
        }else{
            $data = [
            'status' => "fail",
            'message' => "Sorry can't delete "
            ];
        }
        return json_encode($data);
    }
    
}

resources/views/video/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Videos</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{!! URL::to('dashboard') !!}">Home</a></li>
      <li><a href="{!! URL::to('videos') !!}">Videos</a></li>
      <li class="active">Create</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('videos.store')}}" enctype="multipart/form-data" >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create Video</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Title</label>
                                            <input class="form-control" type="text"  name="title" placeholder="Title" >
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Description</label>
                                            <textarea name="description" class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Image</label>
                                            <input class="form-control" type="file" name="images" />
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">File</label>
                                            <input class="form-control" type="file" name="files" />
                                        </div>
                                        <div class="form-group">
                                            <a href="{{route('videos.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/video/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Videos</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{!! URL::to('dashboard') !!}">Home</a></li>
      <li><a href="{!! URL::to('videos') !!}">Videos</a></li>
      <li class="active">Edit</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('videos.update',$video->id)}}" enctype="multipart/form-data" >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update Video</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Title</label>
                                            <input class="form-control" type="text"  name="title" value="{{$video->title}}" placeholder="Title">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Description</label>
                                            <textarea class="form-control" name="description">@if($video->description){{$video->description}}@endif</textarea>
                                        </div>
                                         <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Image</label>
                                            <input class="form-control" type="file" name="images" />
                                        </div>
                                       <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">File</label>
                                            <input class="form-control" type="file" name="files" />
                                        </div>
                                       <form action="{{ route('videos.store', $video->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('videos.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/video/index.blade.php
@extends('layouts.admin')

@section('content')
    
  <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Videos</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{!! URL::to('dashboard') !!}">Home</a></li>
      <li class="active">Videos</li>
    </ol>     
  </div>
  <div class="col-xs-4">
       @if (Session::has('message'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="fa fa-remove"></i>
                                </button>
                            </div>
                        @endif
  </div>
  <div class="col-xs-2 text-right">
   
    <a href="{{route('videos.create')}}" class="btn btn-primary">
      <i class="fa fa-plus" aria-hidden="true"></i> Add 
    </a>
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <table class="table table-hover dataTable table-striped width-full dtr-inline" id='videoTable' >
        <thead>
          <tr>
            <th>No</th>  
            <th>Title</th>
            <th class="action-col">Action</th>
          </tr>
        </thead>
        <tbody> 

        </tbody>
      </table> 
    </div>
  </div>
</div>
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#videoTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('videos.getData') !!}',
        columns: [
            { data: 'id', name:'id'  },
            { data: 'title', name: 'title' },
            { data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        
    });

  
    $('#videoTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/videos/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in Lucky Items view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
   
});
  

</script>
@endpush