routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
header('Access-Control-Allow-Origin: *');

Route::get('/backend/login', 'LoginController@index')->name('login');
Route::post('/backend/login','Auth\LoginController@login');
Route::get('/backend/logout', 'LogoutController@index')->name('logout');
Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::any('users/data', 'UserController@getData')->name('users.getData');
	Route::resource('users', 'UserController');


	Route::any('userlist/data', 'UserListController@getData')->name('userlist.getData');
	Route::resource('userlist','UserListController');
	Route::any('luckyitems/data', 'LuckyItemController@getData')->name('luckyitems.getData');
	Route::resource('luckyitems', 'LuckyItemController');
	//Gallery route
	Route::any('galleries/data', 'GalleryController@getData')->name('galleries.getData');
	Route::resource('galleries', 'GalleryController');

	Route::any('footballTeamList/data', 'FootballTeamListController@getData')->name('footballTeamList.getData');
	Route::resource('footballTeamList','FootballTeamListController');

	Route::any('map/data', 'MapController@getData')->name('map.getData');
	Route::resource('map','MapController');

	Route::any('sliders/data', 'SliderController@getData')->name('sliders.getData');
	Route::resource('sliders','SliderController');

	Route::any('matches/data', 'MatchController@getData')->name('matches.getData');
	Route::resource('matches','MatchController');

	Route::any('videos/data', 'VideoController@getData')->name('videos.getData');
	Route::resource('videos','VideoController');
	
	Route::resource('settings','SettingController');
	
	Route::any('teamList/data', 'TeamListController@getData')->name('teamList.getData');
	Route::resource('teamList','TeamListController');

	Route::any('winning/data', 'WinningController@getData')->name('winning.getData');
	Route::resource('winning','WinningController');
});
Route::get('/','HomePageController@promo');
Route::post('/confirm_yes','HomePageController@confirm');
Route::get('/sess_destroy','HomePageController@destory_session');
Route::get('/home','HomePageController@index')->name('homepage');
Route::resource('userReg','UserReqRegController');
Route::get('/customerlogin','UserReqRegController@showLogin')->name('customer_login');
Route::post('/customerlogin','UserReqRegController@login')->name('customer_login');

Route::get('/customerlogout','UserReqRegController@logout')->name('customer_logout');
Route::group(['middleware' => 'forntendauth:customer'], function () {
	Route::get('/teamedit','HomePageController@teamEdit')->name('teamedit');
	Route::get('/playerlistedit/{id}','HomePageController@playerlistedit')->name('playeredit');
	Route::post('/teamupdate/{id}','HomePageController@teamupdate')->name('teamupdate');
Route::post('/playerlistupdate/{id}','HomePageController@playerlistupdate')->name('playerupdate');
Route::resource('/footballTeamReg','FootballTeamRegController');
Route::get('/teamplayerlist','HomePageController@playerlist')->name('playerlist');
});
Route::get('/luckydraw','HomePageController@luckydraw')->name('luckydraw');

Route::get('/gallery','HomePageController@gallery')->name('gallery');
Route::get('/gallery/{id}','HomePageController@gallery_detail')->name('gallery_detial');

//video gallery
Route::get('/videogallery','HomePageController@videoGallery')->name('videogallery');
Route::get('/videogallery/{id}','HomePageController@videoGallery_detail')->name('videoGallery_detail');
Route::get('/getLuckyItem','HomePageController@getLuckyItem')->name('getluckyitem');
Route::get('/checkLogin','PromotionController@checkLogin')->name('checkLogin');
Route::post('/winningStore','PromotionController@winningStore')->name('winningStore');


Route::resource('/map','MapController');

Route::get('/promotions','HomePageController@promotions')->name('promotions');
Route::get('/term_condition','HomePageController@term_condition')->name('term_condition');
Route::get('/eventlist','HomePageController@eventList')->name('eventlist');
Route::get('/eventdetail/{id}','HomePageController@eventDetail')->name('eventdetail');
Route::get('/matchlist/{id}','HomePageController@matchList')->name('matchList');
//facebook loing

Route::get('facebook_login', 'UserReqRegController@redirectToProvider')->name('fb_login');
Route::get('facebook_login/callback', 'UserReqRegController@handleProviderCallback');

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
class Gallery extends Model implements HasMedia
{
    //
    use SoftDeletes,HasMediaTrait;

     protected $fillable = [
            'title','description'
    ];


    public function getMediaUrl()
    {
        if ($this->hasMedia('gallery')) {
            return $this->getFirstMediaUrl('gallery');
        }
        
    }
    public function getVideoUrl()
    {
        if ($this->hasMedia('gallery_video')) {
            return $this->getFirstMediaUrl('gallery_video');
        }
        
    }
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\RequestGallery;
use App\Repositories\GalleryRepo;
use Illuminate\Validation\Rule; 
use Session;

class GalleryController extends Controller
{
    protected $galleryRepo;

    public function __construct(GalleryRepo $galleryRepo) {
        $this->galleryRepo = $galleryRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        
            return view('gallery.index');     
       
    }

    public function getData(Request $request)
    {
        return $this->galleryRepo->getGalleries($request);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestGallery $request)
    {      
           
        $gallery = $this->galleryRepo->save($request);

        Session::flash('message', 'You have successfully Insert Gallery.');
        return redirect()->route('galleries.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {   
        
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        
        $gallery = $this->galleryRepo->getGallery($id);
        return view('gallery.edit', compact('gallery')); 
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        
        $gallery = $this->galleryRepo->save($request,$id);
        
        Session::flash('message', 'You have successfully Update Gallery.');
        return redirect()->route('galleries.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $deleted = $this->galleryRepo->deleteGallery($id);

            
        if($deleted){
            $data = [
            'status' => "success",
            'message' => "Delete Success"
            ];
        }else{
            $data = [
            'status' => "fail",
            'message' => "Sorry can't delete "
            ];
        }
        return json_encode($data);
    }
    
}

resources/views/gallery/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Gallery</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li><a href="{{route('galleries.index')}}">Gallery</a></li>
      <li class="active">Create</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('galleries.store')}}" enctype="multipart/form-data" >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create Gallery</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Title</label>
                                            <input class="form-control" type="text"  name="title" placeholder="Title" >
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Description</label>
                                            <textarea name="description" class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Image</label>
                                            <input class="form-control" type="file" name="files" />
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Video</label>
                                            <input class="form-control" type="file" name="video_files" />
                                        </div>
                                        <div class="form-group">
                                            <a href="{{route('galleries.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/gallery/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Gallery</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li><a href="{{route('galleries.index')}}">Gallery</a></li>
      <li class="active">Edit</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('galleries.update',$gallery->id)}}" enctype="multipart/form-data" >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update Gallery</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Title</label>
                                            <input class="form-control" type="text"  name="title" value="{{$gallery->title}}" placeholder="Title">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Description</label>
                                            <textarea class="form-control" name="description">@if($gallery->description){{$gallery->description}}@endif</textarea>
                                        </div>
                                       <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Image</label>
                                            <input class="form-control" type="file" name="files" />
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Video</label>
                                            <input class="form-control" type="file" name="video_files" />
                                        </div>
                                       <form action="{{ route('galleries.store', $gallery->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('galleries.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/gallery/index.blade.php
@extends('layouts.admin')

@section('content')
    
  <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Gallery</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li class="active">Gallery</li>
    </ol>     
  </div>
  <div class="col-xs-4">
       @if (Session::has('message'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="fa fa-remove"></i>
                                </button>
                            </div>
                        @endif
  </div>
  <div class="col-xs-2 text-right">
   
    <a href="{{route('galleries.create')}}" class="btn btn-primary">
      <i class="fa fa-plus" aria-hidden="true"></i> Add 
    </a>
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <table class="table table-hover dataTable table-striped width-full dtr-inline" id='galleryTable' >
        <thead>
          <tr>
            <th>No</th>  
            <th>Title</th>
            <th class="action-col">Action</th>
          </tr>
        </thead>
        <tbody> 

        </tbody>
      </table> 
    </div>
  </div>
</div>
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#galleryTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('galleries.getData') !!}',
        columns: [
            { data: 'id', name:'id'  },
            { data: 'title', name: 'title' },
            { data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        
    });

  
    $('#galleryTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/galleries/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in Lucky Items view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
   
});
  

</script>
@endpush