routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
header('Access-Control-Allow-Origin: *');

Route::get('/backend/login', 'LoginController@index')->name('login');
Route::post('/backend/login','Auth\LoginController@login');
Route::get('/backend/logout', 'LogoutController@index')->name('logout');
Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::any('users/data', 'UserController@getData')->name('users.getData');
	Route::resource('users', 'UserController');


	Route::any('userlist/data', 'UserListController@getData')->name('userlist.getData');
	Route::resource('userlist','UserListController');
	Route::any('luckyitems/data', 'LuckyItemController@getData')->name('luckyitems.getData');
	Route::resource('luckyitems', 'LuckyItemController');
	//Gallery route
	Route::any('galleries/data', 'GalleryController@getData')->name('galleries.getData');
	Route::resource('galleries', 'GalleryController');

	Route::any('footballTeamList/data', 'FootballTeamListController@getData')->name('footballTeamList.getData');
	Route::resource('footballTeamList','FootballTeamListController');

	Route::any('map/data', 'MapController@getData')->name('map.getData');
	Route::resource('map','MapController');

	Route::any('sliders/data', 'SliderController@getData')->name('sliders.getData');
	Route::resource('sliders','SliderController');

	Route::any('matches/data', 'MatchController@getData')->name('matches.getData');
	Route::resource('matches','MatchController');

	Route::any('videos/data', 'VideoController@getData')->name('videos.getData');
	Route::resource('videos','VideoController');
	
	Route::resource('settings','SettingController');
	
	Route::any('teamList/data', 'TeamListController@getData')->name('teamList.getData');
	Route::resource('teamList','TeamListController');

	Route::any('winning/data', 'WinningController@getData')->name('winning.getData');
	Route::resource('winning','WinningController');
});
Route::get('/','HomePageController@promo');
Route::post('/confirm_yes','HomePageController@confirm');
Route::get('/sess_destroy','HomePageController@destory_session');
Route::get('/home','HomePageController@index')->name('homepage');
Route::resource('userReg','UserReqRegController');
Route::get('/customerlogin','UserReqRegController@showLogin')->name('customer_login');
Route::post('/customerlogin','UserReqRegController@login')->name('customer_login');

Route::get('/customerlogout','UserReqRegController@logout')->name('customer_logout');
Route::group(['middleware' => 'forntendauth:customer'], function () {
	Route::get('/teamedit','HomePageController@teamEdit')->name('teamedit');
	Route::get('/playerlistedit/{id}','HomePageController@playerlistedit')->name('playeredit');
	Route::post('/teamupdate/{id}','HomePageController@teamupdate')->name('teamupdate');
Route::post('/playerlistupdate/{id}','HomePageController@playerlistupdate')->name('playerupdate');
Route::resource('/footballTeamReg','FootballTeamRegController');
Route::get('/teamplayerlist','HomePageController@playerlist')->name('playerlist');
});
Route::get('/luckydraw','HomePageController@luckydraw')->name('luckydraw');

Route::get('/gallery','HomePageController@gallery')->name('gallery');
Route::get('/gallery/{id}','HomePageController@gallery_detail')->name('gallery_detial');

//video gallery
Route::get('/videogallery','HomePageController@videoGallery')->name('videogallery');
Route::get('/videogallery/{id}','HomePageController@videoGallery_detail')->name('videoGallery_detail');
Route::get('/getLuckyItem','HomePageController@getLuckyItem')->name('getluckyitem');
Route::get('/checkLogin','PromotionController@checkLogin')->name('checkLogin');
Route::post('/winningStore','PromotionController@winningStore')->name('winningStore');


Route::resource('/map','MapController');

Route::get('/promotions','HomePageController@promotions')->name('promotions');
Route::get('/term_condition','HomePageController@term_condition')->name('term_condition');
Route::get('/eventlist','HomePageController@eventList')->name('eventlist');
Route::get('/eventdetail/{id}','HomePageController@eventDetail')->name('eventdetail');
Route::get('/matchlist/{id}','HomePageController@matchList')->name('matchList');
//facebook loing

Route::get('facebook_login', 'UserReqRegController@redirectToProvider')->name('fb_login');
Route::get('facebook_login/callback', 'UserReqRegController@handleProviderCallback');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\UserRequest;
use App\Repositories\UserRepo;
use Illuminate\Validation\Rule; 
use Session;

class UserController extends Controller
{
    protected $userRepo;

    public function __construct(UserRepo $userRepo) {
        $this->userRepo = $userRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        
            return view('user.index');     
       
    }

    public function getData(Request $request)
    {
        return $this->userRepo->getUsers($request);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {      
           
        $user = $this->userRepo->save($request);

        Session::flash('message', 'You have successfully Insert User.');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {   
        
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        
        $user = $this->userRepo->getUser($id);
        return view('user.edit', compact('user')); 
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        
        $user = $this->userRepo->save($request,$id);
        
        Session::flash('message', 'You have successfully Update User.');
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $deleted = $this->userRepo->deleteUser($id);

            
        if($deleted){
            $data = [
            'status' => "success",
            'message' => "Delete Success"
            ];
        }else{
            $data = [
            'status' => "fail",
            'message' => "Sorry can't delete "
            ];
        }
        return json_encode($data);
    }
    
}

resources/views/user/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Users</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li class="active">Users</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('users.store')}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create User</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Email</label>
                                            <input class="form-control" type="email"  name="email" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Password</label>
                                            <input class="form-control" type="password"  name="password" placeholder="Password">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="inputPassword" class="">Confirm Password</label>
                                            <input type="password" class="form-control" name="password_confirmation"  placeholder="Confirm Password">
                                        </div>
                                       
                                        <div class="form-group">
                                            <a href="{{route('users.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Users</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li class="active">Users</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('users.update',$user->id)}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update User</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" value="{{$user->name}}" placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Email</label>
                                            <input class="form-control" type="email"  name="email" value="{{$user->email}}" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Password</label>
                                            <input class="form-control" type="password"  name="password" placeholder="Password">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="inputPassword" class="">Confirm Password</label>
                                            <input type="password" class="form-control" name="password_confirmation"  placeholder="Confirm Password">
                                        </div>
                                        
                                       <form action="{{ route('users.store', $user->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('users.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.admin')
@section('content')    
  <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Users</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li class="active">Users</li>
    </ol>     
  </div>
  <div class="col-xs-4">
    @if (Session::has('message'))
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ Session::get('message') }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="fa fa-remove"></i>
          </button>
      </div>
    @endif
  </div>
  <div class="col-xs-2 text-right">   
    <a href="{{route('users.create')}}" class="btn btn-primary">
      <i class="fa fa-plus" aria-hidden="true"></i> Add 
    </a>   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <table class="table table-hover dataTable table-striped width-full dtr-inline" id='userTable' >
        <thead>
          <tr>
            <th>No</th>  
            <th>Name</th>
            <th>Email</th>
            <th class="action-col">Action</th>
          </tr>
        </thead>
        <tbody> 

        </tbody>
      </table> 
    </div>
  </div>
</div>
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#userTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('users.getData') !!}',
        columns: [
            { data: 'id', name:'id'  },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        
    });

  
    $('#userTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/users/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in student view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
   
});
  

</script>
@endpush