routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
header('Access-Control-Allow-Origin: *');

Route::get('/backend/login', 'LoginController@index')->name('login');
Route::post('/backend/login','Auth\LoginController@login');
Route::get('/backend/logout', 'LogoutController@index')->name('logout');
Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get('dashboard','HomeController@index')->name('dashboard');

	Route::any('users/data', 'UserController@getData')->name('users.getData');
	Route::resource('users', 'UserController');


	Route::any('userlist/data', 'UserListController@getData')->name('userlist.getData');
	Route::resource('userlist','UserListController');
	Route::any('luckyitems/data', 'LuckyItemController@getData')->name('luckyitems.getData');
	Route::resource('luckyitems', 'LuckyItemController');
	//Gallery route
	Route::any('galleries/data', 'GalleryController@getData')->name('galleries.getData');
	Route::resource('galleries', 'GalleryController');

	Route::any('footballTeamList/data', 'FootballTeamListController@getData')->name('footballTeamList.getData');
	Route::resource('footballTeamList','FootballTeamListController');

	Route::any('map/data', 'MapController@getData')->name('map.getData');
	Route::resource('map','MapController');

	Route::any('sliders/data', 'SliderController@getData')->name('sliders.getData');
	Route::resource('sliders','SliderController');

	Route::any('matches/data', 'MatchController@getData')->name('matches.getData');
	Route::resource('matches','MatchController');

	Route::any('videos/data', 'VideoController@getData')->name('videos.getData');
	Route::resource('videos','VideoController');
	
	Route::resource('settings','SettingController');
	
	Route::any('teamList/data', 'TeamListController@getData')->name('teamList.getData');
	Route::resource('teamList','TeamListController');

	Route::any('winning/data', 'WinningController@getData')->name('winning.getData');
	Route::resource('winning','WinningController');
});
Route::get('/','HomePageController@promo');
Route::post('/confirm_yes','HomePageController@confirm');
Route::get('/sess_destroy','HomePageController@destory_session');
Route::get('/home','HomePageController@index')->name('homepage');
Route::resource('userReg','UserReqRegController');
Route::get('/customerlogin','UserReqRegController@showLogin')->name('customer_login');
Route::post('/customerlogin','UserReqRegController@login')->name('customer_login');

Route::get('/customerlogout','UserReqRegController@logout')->name('customer_logout');
Route::group(['middleware' => 'forntendauth:customer'], function () {
	Route::get('/teamedit','HomePageController@teamEdit')->name('teamedit');
	Route::get('/playerlistedit/{id}','HomePageController@playerlistedit')->name('playeredit');
	Route::post('/teamupdate/{id}','HomePageController@teamupdate')->name('teamupdate');
Route::post('/playerlistupdate/{id}','HomePageController@playerlistupdate')->name('playerupdate');
Route::resource('/footballTeamReg','FootballTeamRegController');
Route::get('/teamplayerlist','HomePageController@playerlist')->name('playerlist');
});
Route::get('/luckydraw','HomePageController@luckydraw')->name('luckydraw');

Route::get('/gallery','HomePageController@gallery')->name('gallery');
Route::get('/gallery/{id}','HomePageController@gallery_detail')->name('gallery_detial');

//video gallery
Route::get('/videogallery','HomePageController@videoGallery')->name('videogallery');
Route::get('/videogallery/{id}','HomePageController@videoGallery_detail')->name('videoGallery_detail');
Route::get('/getLuckyItem','HomePageController@getLuckyItem')->name('getluckyitem');
Route::get('/checkLogin','PromotionController@checkLogin')->name('checkLogin');
Route::post('/winningStore','PromotionController@winningStore')->name('winningStore');


Route::resource('/map','MapController');

Route::get('/promotions','HomePageController@promotions')->name('promotions');
Route::get('/term_condition','HomePageController@term_condition')->name('term_condition');
Route::get('/eventlist','HomePageController@eventList')->name('eventlist');
Route::get('/eventdetail/{id}','HomePageController@eventDetail')->name('eventdetail');
Route::get('/matchlist/{id}','HomePageController@matchList')->name('matchList');
//facebook loing

Route::get('facebook_login', 'UserReqRegController@redirectToProvider')->name('fb_login');
Route::get('facebook_login/callback', 'UserReqRegController@handleProviderCallback');

app/LuckyItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class LuckyItem extends Model
{
    //
    use SoftDeletes;

     protected $fillable = [
            'name','message','item_count','background_color','status'
    ];
}

app/Http/Controllers/LuckyItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\RequestItems;
use App\Repositories\LuckyItemRepo;
use Illuminate\Validation\Rule; 
use Session;

class LuckyItemController extends Controller
{
    protected $luckyItemRepo;

    public function __construct(LuckyItemRepo $luckyItemRepo) {
        $this->luckyItemRepo = $luckyItemRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        
            return view('luckyitem.index');     
       
    }

    public function getData(Request $request)
    {
        return $this->luckyItemRepo->getLuckyItems($request);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('luckyitem.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestItems $request)
    {      
           
        $user = $this->luckyItemRepo->save($request);

        Session::flash('message', 'You have successfully Insert LuckyItems.');
        return redirect()->route('luckyitems.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {   
        
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        
        $item = $this->luckyItemRepo->getLuckyItem($id);
        return view('luckyitem.edit', compact('item')); 
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        
        $item = $this->luckyItemRepo->save($request,$id);
        
        Session::flash('message', 'You have successfully Update Item.');
        return redirect()->route('luckyitems.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {   
        $deleted = $this->luckyItemRepo->deleteLuckyItem($id);

            
        if($deleted){
            $data = [
            'status' => "success",
            'message' => "Delete Success"
            ];
        }else{
            $data = [
            'status' => "fail",
            'message' => "Sorry can't delete "
            ];
        }
        return json_encode($data);
    }
    
}

resources/views/luckyitem/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Lucky Items</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li><a href="{{route('luckyitems.index')}}">Lucky Items</a></li>
      <li class="active">Create</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('luckyitems.store')}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create Lucky Items</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" placeholder="Name" >
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Messsage</label>
                                            <textarea name="message" class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="item_count" class="col-form-label">Count</label>
                                            <input class="form-control" type="text"  name="item_count" placeholder="Count" >
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Background Color</label>
                                            <input class="form-control" type="color"  name="background_color" />
                                        </div>
                                        
                                        
                                       
                                        <div class="form-group">
                                            <a href="{{route('luckyitems.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/luckyitem/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Lucky Items</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li><a href="{{route('luckyitems.index')}}">Lucky Item</a></li>
      <li class="active">Edit</li>
    </ol>     
  </div>
  <div class="col-xs-6 text-right">
   
    
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('luckyitems.update',$item->id)}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update Lucky Item</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" value="{{$item->name}}" placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Message</label>
                                            <textarea class="form-control" name="message">@if($item->message){{$item->message}}@endif</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="item_count" class="col-form-label">Count</label>
                                            <input class="form-control" type="text"  name="item_count" placeholder="Count" value="{{$item->item_count}}">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Background Color</label>
                                            <input class="form-control" type="color"  name="background_color" value="{{$item->background_color}}" />
                                        </div>
                                        
                                        
                                        
                                       <form action="{{ route('luckyitems.store', $item->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('luckyitems.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
    </div>
  </div>
</div>
@endsection

resources/views/luckyitem/index.blade.php
@extends('layouts.admin')

@section('content')
    
  <div class="page-header">
  <div class="col-xs-6">
    <h1 class="page-title">Lucky Items</h1>
    <ol class="breadcrumb breadcrumb-arrow">
      <li><a href="{{route('dashboard')}}">Home</a></li>
      <li class="active">Lucky Items</li>
    </ol>     
  </div>
  <div class="col-xs-4">
       @if (Session::has('message'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="fa fa-remove"></i>
                                </button>
                            </div>
                        @endif
  </div>
  <div class="col-xs-2 text-right">
   
    <!-- <a href="{{route('luckyitems.create')}}" class="btn btn-primary">
      <i class="fa fa-plus" aria-hidden="true"></i> Add 
    </a> -->
   
  </div>
</div>
<div class="clearfix"></div>
<div class="page-content" >
  <div class="panel">
    <div class="panel-body container-fluid" id="tbl-user">
      <div class="success-alert-area"> </div>
      <div class="clearfix sp-margin-sm"></div>
      <table class="table table-hover dataTable table-striped width-full dtr-inline" id='luckyItemTable' >
        <thead>
          <tr>
            <th>No</th>  
            <th>Name</th>
            <th>Count</th>
            <th>Message</th>
            <th>Background Color</th>
            <th class="action-col">Action</th>
          </tr>
        </thead>
        <tbody> 

        </tbody>
      </table> 
    </div>
  </div>
</div>
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#luckyItemTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('luckyitems.getData') !!}',
        columns: [
            { data: 'id', name:'id'  },
            { data: 'name', name: 'name' },
            { data: 'item_count', name: 'item_count' },
            { data: 'message', name: 'message' },
            { data: 'background_color', name: 'background_color' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        
    });

  
    $('#luckyItemTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/luckyitems/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in Lucky Items view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
   
});
  

</script>
@endpush